# GridFormer_mixed.yml  (Validation Hızlandırması ile Güncellendi)

# --------------------------------------------------
# General settings
# --------------------------------------------------
name: CombinedWeather_GridFormer_Mixed_6850_mixed6868
model_type: MIMOModel
scale: 1
num_gpu: 1
manual_seed: 100

# --------------------------------------------------
# Dataset and data-loader settings
# --------------------------------------------------
datasets:
  train:
    name: TrainSet_Allweather
    type: PairedImageDataset
    dataroot_gt: /content/drive/MyDrive/datasets/combined_weather/train/gt1
    dataroot_lq: /content/drive/MyDrive/datasets/combined_weather/train/input1
    geometric_augs: true
    meta_info_file: ~
    filename_tmpl: '{}'
    io_backend:
      type: disk
    io_memory: false
    gt_size: 128
    use_hflip: true
    use_rot: true
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 12
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet_Allweather
    type: PairedImageDataset
    dataroot_gt: /content/drive/MyDrive/datasets/combined_weather/train/gt1
    dataroot_lq: /content/drive/MyDrive/datasets/combined_weather/train/input1
    filename_tmpl: '{}'
    io_backend:
      type: disk
    io_memory: false

# --------------------------------------------------
# Network structure
# --------------------------------------------------
network_g:
  type: GridFormer
  in_channels: 3
  out_channels: 3
  dim: 64
  kernel_size: 3
  stride: 2
  height: 3
  width: 6
  num_blocks: [1, 2, 4]
  heads: [2, 4, 8]
  attention: true
  windows: 4
  sample_rate_trunk: [4,2,2]
  scale: 1
  use_innovative_attn: true
  scales: [1, 2, 4]
  downsample_factor: 2
  drop_path_prob: 0.0

# --------------------------------------------------
# Paths
# --------------------------------------------------
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# --------------------------------------------------
# Training settings
# --------------------------------------------------
train:
  ema_decay: 0.999
  accumulation_steps: 4
  optim_g:
    type: AdamW
    lr: 1e-4
    weight_decay: 1e-2
    betas: [0.9, 0.999]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 6400
    eta_min: 1e-6

  total_iter: 6400
  warmup_iter: 400

  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      conv5_4: 1
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 0.1
    style_weight: 0
    criterion: l1

# --------------------------------------------------
# Validation settings
# --------------------------------------------------
val:
  val_freq: 4000
  save_img: true
  # <─ DEĞİŞİKLİK: Daha büyük tile'lar ve daha küçük örtüşme ile validasyon hızlandırıldı.
  tile_size: 192
  tile_overlap: 24
  use_tta: false
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true
      better: higher
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: true
      better: higher

# --------------------------------------------------
# Logging
# --------------------------------------------------
logger:
  print_freq: 100
  save_checkpoint_freq: 4000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# --------------------------------------------------
# Distributed training
# --------------------------------------------------
dist_params:
  backend: nccl
  port: 29500